apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world
spec:
  entrypoint: hello
  serviceAccountName: argo-workflow
  templates:
  - name: hello
    container:
      image: busybox:1.36
      command: [echo]
      args: ["hello from argo workflows"]
